FROM ubuntu:16.10

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    libgstrtspserver-1.0-dev \
    git \
    ca-certificates \
    cmake &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD build_image/build_rtspatt_inside_docker.sh /usr/local/bin/build_rtspatt.sh

CMD build_rtspatt.sh
